# Generated by Django 2.2.5 on 2020-11-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='blog.Tag', verbose_name='Комментарии'),
        ),
    ]
